FC=gfortran
WARNINGS = -Wall
FCFLAGS = -O1 -fcheck=all -fopenmp ${WARNINGS}
DEBUGFLAGS = -g -ffpe-trap=zero,invalid,overflow,underflow -pg
EXEC_FILE = main
EXEC_PATH = ./bin/

# Modules in compilation order.
OBJ = src/ErrorInstance.o \
	src/ErrorHandler.o \
	src/ErrorCriteria.o \
	src/Result.o \
	example/example_usage.o

OBJECTS = $(notdir $(OBJ))

VPATH = src \
	example

# The commands:
#   make main: Compile and create exe.
#   make run: Run the compiled exe.
#   make clean: Remove compiled files.
$(EXEC_FILE): $(OBJECTS)
	$(FC) $(FCFLAGS) $(DEBUGFLAGS) -o $(EXEC_PATH)$@ $^
%.o: %.f90
	$(FC) -c $(FCFLAGS) $(DEBUGFLAGS) $<
run:
	$(EXEC_PATH)$(EXEC_FILE)
clean:
	rm -f *.mod *.o *.stackdump
